import { firebaseConfig } from './firebase-config.js';
let auth,store,currentUser=null,ready=false,pending=false,subscriptions=[];
const loaded=new Set();
function status(text){document.getElementById('syncStatus').textContent=text;}
function reportError(e){console.error(e);status('İşlem tamamlanamadı.');alert(e.message||'İşlem başarısız oldu.');}
async function action(fn){if(pending)return;if(!currentUser||!ready){alert('Verilerin yüklenmesini ve bağlantıyı bekleyin.');return;}pending=true;const buttons=[...document.querySelectorAll('button')].filter(b=>!b.disabled);buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){reportError(e);}finally{pending=false;buttons.forEach(b=>b.disabled=false);}}
let api;
function ref(kind,id){return api.doc(store,'users',currentUser.uid,kind,id);}
function withoutId(obj){const {id,...data}=obj;return data;}
function ensureNumber(id,integer=false,min=0){const value=Number(document.getElementById(id).value);if(!Number.isFinite(value)||value<min||(integer&&!Number.isInteger(value)))throw Error('Miktar ve fiyat alanlarını kontrol edin.');return value;}
function safeId(id){if(typeof id!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(id))throw Error('Kayıt kimliği geçersiz.');return id;}
function normalizeProduct(p){return {...p,name:p.name||'',sku:p.sku||'',cat:p.cat??p.category??'',supplier:p.supplier||'',note:p.note||'',buy:Number(p.buy??p.buy_price??0),buyCase:Number(p.buyCase??p.buy_case_price??0),whole:Number(p.whole??p.wholesale_price??0),retail:Number(p.retail??p.retail_price??0),caseQty:Number(p.caseQty??p.case_qty??1),stock:Number(p.stock??p.stock_units??0),min:Number(p.min??p.min_stock??0),image:validImage(p.image)?p.image:''};}
function normalizeSale(s){return {...s,date:s.date??s.sale_date??'',productId:s.productId??s.product_id,type:s.type??s.sale_type??'retail',unit:s.unit||'unit',qty:Number(s.qty??s.quantity_units??0),units:Number(s.units??s.quantity_units??0),price:Number(s.price??0),total:Number(s.total??s.total_amount??0),cost:Number(s.cost??s.cost_amount??0),profit:Number(s.profit??s.profit_amount??0),note:s.note||''};}
function normalizeExpense(e){return {...e,date:e.date??e.expense_date??'',cat:e.cat??e.category??'',amount:Number(e.amount||0),note:e.note||''};}
async function saveProduct(){return action(async()=>{
 if(imageLoading)throw Error('Görselin hazırlanmasını bekleyin.');const id=safeId($('pId').value||crypto.randomUUID()),old=product(id);
 const p={...old,id,name:$('pName').value.trim(),sku:$('pSku').value.trim(),cat:$('pCat').value.trim(),supplier:$('pSupplier').value.trim(),note:$('pNote').value.trim(),buy:ensureNumber('pBuy'),buyCase:ensureNumber('pBuyCase'),whole:ensureNumber('pWhole'),retail:ensureNumber('pRetail'),caseQty:ensureNumber('pCaseQty',true,1),stock:ensureNumber('pStock',true),min:ensureNumber('pMin',true),image:productImage};
 if(!p.name)throw Error('Ürün adı zorunlu.');if($('pBuyCase').value==='')p.buyCase=p.buy*p.caseQty;
 await api.runTransaction(store,async tx=>{const target=ref('products',id),snap=await tx.get(target);if(old&&(!snap.exists()||normalizeProduct(snap.data()).stock!==editingStock))throw Error('Stok başka bir işlemle değişti. Ürünü yeniden açın.');if(!old&&snap.exists())throw Error('Kayıt kimliği çakıştı.');tx.set(target,withoutId(p));});cancelProduct();clearImage();status('Ürün kaydedildi.');
 });}
async function deleteProduct(id){if(db.sales.some(s=>s.productId===id)){alert('Satış kaydı bulunan ürün silinemez.');return;}if(!confirm('Ürün silinsin mi?'))return;return action(async()=>{await api.runTransaction(store,async tx=>{const target=ref('products',safeId(id)),snap=await tx.get(target);if(!snap.exists())return;if(snap.data().saleCount>0)throw Error('Bu ürünün satış kayıtları var.');tx.delete(target);});});}
async function saveSale(){return action(async()=>{
 const p=product($('sProduct').value);if(!p)throw Error('Ürün seçin.');const qty=ensureNumber('sQty',true,1),price=ensureNumber('sPrice'),date=$('sDate').value;if(!date)throw Error('Tarih seçin.');const unit=$('sUnit').value,type=$('sType').value,note=$('sNote').value.trim(),saleId=crypto.randomUUID();
 await api.runTransaction(store,async tx=>{const pr=ref('products',p.id),snap=await tx.get(pr);if(!snap.exists())throw Error('Ürün bulunamadı.');const fresh=normalizeProduct(snap.data()),units=qty*(unit==='case'?fresh.caseQty:1);if(units>fresh.stock)throw Error('Yetersiz stok. Mevcut: '+fresh.stock+' adet.');const total=qty*price,cost=units*fresh.buy;tx.update(pr,{stock:fresh.stock-units,saleCount:Number(snap.data().saleCount||0)+1});tx.set(ref('sales',saleId),{date,productId:p.id,productName:fresh.name,type,unit,qty,units,price,total,cost,profit:total-cost,note});});$('sQty').value=1;$('sNote').value='';status('Satış kaydedildi, stok güncellendi.');
 });}
async function deleteSale(id){if(!confirm('Satış silinsin ve stok geri eklensin mi?'))return;return action(async()=>{await api.runTransaction(store,async tx=>{const sr=ref('sales',safeId(id)),snap=await tx.get(sr);if(!snap.exists())return;const s=normalizeSale(snap.data()),pr=ref('products',s.productId),ps=await tx.get(pr);if(!ps.exists())throw Error('Ürün bulunamadı; stok iadesi yapılamadı.');tx.update(pr,{stock:normalizeProduct(ps.data()).stock+s.units,saleCount:Math.max(0,Number(ps.data().saleCount||0)-1)});tx.delete(sr);});});}
async function saveExpense(){return action(async()=>{const amount=ensureNumber('eAmount');if(amount<=0||!$('eDate').value)throw Error('Tarih ve pozitif tutar girin.');await api.setDoc(ref('expenses',crypto.randomUUID()),{date:$('eDate').value,cat:$('eCat').value.trim(),amount,note:$('eNote').value.trim()});cancelExpense();});}
async function deleteExpense(id){if(confirm('Gider silinsin mi?'))return action(()=>api.deleteDoc(ref('expenses',safeId(id))));}
function validateBackup(data){
 if(!data||!['products','sales','expenses'].every(k=>Array.isArray(data[k])))throw Error('Yedek biçimi geçersiz.');const result={products:data.products.map(normalizeProduct),sales:data.sales.map(normalizeSale),expenses:data.expenses.map(normalizeExpense)};
 for(const kind of ['products','sales','expenses']){const ids=new Set();for(const row of result[kind]){safeId(row.id);if(ids.has(row.id))throw Error('Yedekte yinelenen kimlik var.');ids.add(row.id);}}
 for(const p of result.products){if(!p.name||['buy','buyCase','whole','retail','caseQty','stock','min'].some(k=>!Number.isFinite(p[k])||p[k]<0)||!Number.isInteger(p.caseQty)||p.caseQty<1||!Number.isInteger(p.stock)||!Number.isInteger(p.min))throw Error('Yedekte geçersiz ürün var.');}
 for(const s of result.sales){if(!result.products.some(p=>p.id===s.productId)||!/^\d{4}-\d{2}-\d{2}$/.test(s.date)||!['wholesale','retail'].includes(s.type)||['qty','units','price','total','cost','profit'].some(k=>!Number.isFinite(s[k]))||s.units<0)throw Error('Yedekte geçersiz satış var.');}
 for(const e of result.expenses){if(!Number.isFinite(e.amount)||e.amount<0||!/^\d{4}-\d{2}-\d{2}$/.test(e.date))throw Error('Yedekte geçersiz gider var.');}
 for(const p of result.products)p.saleCount=result.sales.filter(s=>s.productId===p.id).length;return result;
}
async function restore(){const file=$('restoreFile').files[0];if(!file){alert('JSON yedek dosyası seçin.');return;}return action(async()=>{const restored=validateBackup(JSON.parse(await file.text()));const operations=[];for(const k of ['products','sales','expenses']){const targetIds=new Set(restored[k].map(x=>x.id));for(const row of db[k])if(!targetIds.has(row.id))operations.push(['delete',k,row.id]);for(const row of restored[k])operations.push(['set',k,row.id,withoutId(row)]);}if(operations.length>450)throw Error('Yedek tek işlem sınırını aşıyor. Veriler değiştirilmedi.');if(!confirm('Mevcut veriler yedekle değiştirilecek. Güncel yedeğinizi aldıysanız devam edin.'))return;const batch=api.writeBatch(store);for(const [op,k,id,data] of operations)if(op==='delete')batch.delete(ref(k,id));else batch.set(ref(k,id),data);await batch.commit();status('Yedek geri yüklendi.');});}
async function login(event){event.preventDefault();$('authMessage').textContent='Giriş yapılıyor…';try{await api.signInWithEmailAndPassword(auth,$('loginEmail').value.trim(),$('loginPassword').value);$('authMessage').textContent='';}catch(e){$('authMessage').textContent='Giriş başarısız: '+e.code;}}
async function loginGithub(){try{await api.signInWithPopup(auth,new api.GithubAuthProvider());}catch(e){$('authMessage').textContent='GitHub girişi başarısız: '+e.code;}}
async function resetPassword(){const email=$('loginEmail').value.trim();if(!email){$('authMessage').textContent='Önce e-posta adresinizi girin.';return;}try{await api.sendPasswordResetEmail(auth,email);$('authMessage').textContent='Şifre sıfırlama isteği alındı. E-postanızı kontrol edin.';}catch(e){$('authMessage').textContent='İşlem başarısız: '+e.code;}}
async function logout(){if(pending)return;await api.signOut(auth);}
Object.assign(window,{saveProduct,deleteProduct,saveSale,deleteSale,saveExpense,deleteExpense,restore,login,loginGithub,resetPassword,logout});
async function start(){
 if(!firebaseConfig.apiKey||!firebaseConfig.projectId){$('setupBox').style.display='block';return;}
 try{
 const version='12.19.0',base=`https://www.gstatic.com/firebasejs/${version}/`,[app,authentication,firestore]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-auth.js'),import(base+'firebase-firestore.js')]);api={...authentication,...firestore};const instance=app.initializeApp(firebaseConfig);auth=api.getAuth(instance);store=api.getFirestore(instance);$('loginBox').style.display='block';
 api.onAuthStateChanged(auth,user=>{subscriptions.forEach(fn=>fn());subscriptions=[];ready=false;loaded.clear();currentUser=user;db={products:[],sales:[],expenses:[]};renderAll();$('authScreen').style.display=user?'none':'grid';$('appShell').style.display=user?'block':'none';if(!user)return;$('userInfo').textContent=user.email||'Kullanıcı';status('Veriler yükleniyor…');const uid=user.uid;
 for(const [kind,normalize] of [['products',normalizeProduct],['sales',normalizeSale],['expenses',normalizeExpense]]){const col=api.collection(store,'users',uid,kind);subscriptions.push(api.onSnapshot(col,snapshot=>{if(currentUser?.uid!==uid)return;db[kind]=snapshot.docs.map(d=>normalize({...d.data(),id:d.id}));loaded.add(kind);ready=loaded.size===3;renderAll();if(ready)status(snapshot.metadata.hasPendingWrites?'Kaydediliyor…':snapshot.metadata.fromCache?'Önbellek verileri gösteriliyor.':'Bulut verileri güncel.');},e=>{ready=false;loaded.delete(kind);status('Veriler yüklenemedi: '+e.code);}));}
 });
 }catch(e){$('authMessage').textContent='Firebase yüklenemedi: '+e.message;}
}
start();
