let productImage='', imageLoading=false, imageGeneration=0;
function validImage(value){return typeof value==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(value)&&value.length<300000;}
function imageTag(p,cls=''){return validImage(p.image)?`<img class="${cls}" src="${p.image}" alt="${esc(p.name)}">`:'<span class="muted">Görsel yok</span>';}
function setImage(value){productImage=validImage(value)?value:'';const img=document.getElementById('pImagePreview');img.hidden=!productImage;if(productImage)img.src=productImage;else img.removeAttribute('src');}
function clearImage(){imageGeneration++;imageLoading=false;setImage('');document.getElementById('pImage').value='';document.getElementById('imageStatus').textContent='';}
async function selectImage(event){
 const file=event.target.files[0];if(!file)return;const generation=++imageGeneration;
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024){imageLoading=false;document.getElementById('imageStatus').textContent='Görsel seçimi geçersiz.';alert('En fazla 15 MB boyutunda JPEG, PNG veya WebP seçin.');event.target.value='';return;}
 imageLoading=true;document.getElementById('imageStatus').textContent='Görsel hazırlanıyor…';
 try{
  const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'}),scale=Math.min(1,700/Math.max(bitmap.width,bitmap.height));
  const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
  let quality=.85,value=canvas.toDataURL('image/jpeg',quality);while(value.length>240000&&quality>.25){quality-=.1;value=canvas.toDataURL('image/jpeg',quality);}
  if(value.length>240000)throw Error('Görsel sıkıştırılamadı. Daha küçük bir görsel seçin.');
  if(generation===imageGeneration){setImage(value);document.getElementById('imageStatus').textContent='Görsel hazır.';}
 }catch(e){if(generation===imageGeneration){alert(e.message||'Görsel okunamadı.');document.getElementById('imageStatus').textContent='Görsel hazırlanamadı.';}}
 finally{if(generation===imageGeneration)imageLoading=false;}
}
function filteredProducts(){const q=($('productSearch').value||'').toLocaleLowerCase('tr-TR'),cat=$('stockCategory').value,status=$('stockFilter').value;return db.products.filter(p=>(`${p.name} ${p.sku||''} ${p.cat||''} ${p.supplier||''}`).toLocaleLowerCase('tr-TR').includes(q)&&(!cat||p.cat===cat)&&(!status||(status==='low'&&p.stock<=p.min)||(status==='zero'&&p.stock===0)||(status==='available'&&p.stock>0))).sort((a,b)=>a.name.localeCompare(b.name,'tr'));}
function categories(){return [...new Set(db.products.map(p=>p.cat).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr'));}
function renderStockReport(){
 for(const id of ['stockCategory','priceCategory']){const select=$(id),old=select.value;select.innerHTML='<option value="">Tümü</option>'+categories().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');select.value=categories().includes(old)?old:'';}
 const rows=filteredProducts();$('stockSummary').textContent=`${rows.length} ürün · ${num(rows.reduce((a,p)=>a+p.stock,0))} adet · Stok maliyeti: ${money(rows.reduce((a,p)=>a+p.stock*p.buy,0))} · Toptan stok değeri: ${money(rows.reduce((a,p)=>a+p.stock*p.whole,0))} · Perakende stok değeri: ${money(rows.reduce((a,p)=>a+p.stock*p.retail,0))} · Kritik ürün: ${rows.filter(p=>p.stock<=p.min).length}`;
}
const stockHeaders=['Ürün','Stok kodu','Kategori','Tedarikçi','Açıklama','Alış/adet','Alış/koli','Toptan/adet','Perakende/adet','Koli içi adet','Stok/adet','Tam koli','Artan adet','Minimum stok','Stok durumu','Stok maliyeti','Toptan stok değeri','Perakende stok değeri'];
function stockRow(p){return [p.name,p.sku,p.cat,p.supplier,p.note,p.buy,p.buyCase,p.whole,p.retail,p.caseQty,p.stock,Math.floor(p.stock/p.caseQty),p.stock%p.caseQty,p.min,p.stock===0?'Stok yok':p.stock<=p.min?'Kritik':'Normal',p.stock*p.buy,p.stock*p.whole,p.stock*p.retail];}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function exportStockExcel(){const rows=filteredProducts();writeWorkbook([{name:'Ürün Stok Detayı',rows:[stockHeaders,...rows.map(stockRow)]},{name:'Özet',rows:[['Rapor tarihi',today()],['Ürün',rows.length],['Stok/adet',rows.reduce((a,p)=>a+p.stock,0)],['Stok maliyeti',rows.reduce((a,p)=>a+p.stock*p.buy,0)],['Toptan stok değeri',rows.reduce((a,p)=>a+p.stock*p.whole,0)],['Perakende stok değeri',rows.reduce((a,p)=>a+p.stock*p.retail,0)],['Kritik ürün',rows.filter(p=>p.stock<=p.min).length]]}],`stok-detay-${today()}.xlsx`);}
function exportExcel(){const {sales,expenses}=reportData();writeWorkbook([{name:'Satışlar',rows:[['Tarih','Ürün','Tür','Birim','Miktar','Adet','Birim fiyat','Satış','Maliyet','Brüt kâr','Açıklama'],...sales.map(s=>[s.date,product(s.productId)?.name||s.productName||'',s.type==='wholesale'?'Toptan':'Perakende',s.unit==='case'?'Koli':'Adet',s.qty,s.units,s.price,s.total,s.cost,s.profit,s.note])]},{name:'Giderler',rows:[['Tarih','Tür','Açıklama','Tutar'],...expenses.map(e=>[e.date,e.cat,e.note,e.amount])]},{name:'Dönem Özeti',rows:[['Başlangıç',$('rf').value],['Bitiş',$('rt').value],['Toplam satış',sales.reduce((a,s)=>a+s.total,0)],['Brüt kâr',sales.reduce((a,s)=>a+s.profit,0)],['Gider',expenses.reduce((a,e)=>a+e.amount,0)],['Net sonuç',sales.reduce((a,s)=>a+s.profit,0)-expenses.reduce((a,e)=>a+e.amount,0)]]}],`satis-raporu-${today()}.xlsx`);}
function tableHTML(headers,rows){return `<table><thead><tr>${headers.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
let printBusy=false;
async function printDocument(title,html,landscape=false){
 if(printBusy)return;printBusy=true;const frame=document.createElement('iframe');frame.title=title;frame.style.cssText='position:fixed;left:-10000px;top:0;width:1000px;height:800px';document.body.append(frame);
 const doc=frame.contentDocument;doc.open();doc.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4 ${landscape?'landscape':'portrait'};margin:12mm}body{font:11px Arial,sans-serif;color:#17202a}h1{font-size:21px}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #ccc;padding:7px;text-align:left;overflow-wrap:anywhere}th{background:#eef1f5}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}.price-image,.image-placeholder{width:30mm!important;height:30mm!important;min-width:30mm;display:block;object-fit:contain}.image-placeholder{border:1px solid #ddd;display:flex;align-items:center;justify-content:center;color:#777}.price{font-size:15px;font-weight:bold;white-space:nowrap}.muted{color:#667085}.price-table td{padding:3mm}.price-table td:first-child{width:34mm}button{margin:12px 0}@media print{button{display:none}}</style></head><body><button onclick="window.print()">PDF olarak kaydet / Yazdır</button><h1>${esc(title)}</h1><p>${esc(today())}</p>${html}</body></html>`);doc.close();
 frame.contentWindow.onafterprint=()=>frame.remove();
 try{await Promise.all([...doc.images].map(img=>img.decode().catch(()=>{})));frame.contentWindow.focus();frame.contentWindow.print();}
 finally{printBusy=false;setTimeout(()=>frame.remove(),120000);}
}
function printPriceList(type){if(!['wholesale','retail'].includes(type))return;const cat=$('priceCategory').value,available=$('priceStock').value==='available',rows=db.products.filter(p=>(!cat||p.cat===cat)&&(!available||p.stock>0)).sort((a,b)=>a.name.localeCompare(b.name,'tr'));if(!rows.length){alert('Seçilen filtrelerde ürün yok.');return;}const title=type==='wholesale'?'Toptan Fiyat Listesi':'Perakende Fiyat Listesi';return printDocument(title,`<table class="price-table"><thead><tr><th>Görsel</th><th>Ürün bilgisi</th><th>Adet fiyatı</th><th>Koli fiyatı</th></tr></thead><tbody>${rows.map(p=>{const price=type==='wholesale'?p.whole:p.retail;return `<tr><td>${validImage(p.image)?imageTag(p,'price-image'):'<div class="image-placeholder">Görsel yok</div>'}</td><td><b>${esc(p.name)}</b><p>${esc(p.sku||'')} ${esc(p.cat||'')}</p><p>${esc(p.note||'')}</p><span class="muted">Koli içi: ${num(p.caseQty)} adet</span></td><td class="price">${money(price)}</td><td class="price">${money(price*p.caseQty)}</td></tr>`;}).join('')}</tbody></table>`);}
function printStockReport(){const rows=filteredProducts();if(!rows.length){alert('Seçilen filtrelerde ürün yok.');return;}return printDocument('Detaylı Ürün / Stok Raporu',`<p>${esc($('stockSummary').textContent)}</p><p>Arama: ${esc($('productSearch').value||'Tümü')} · Kategori: ${esc($('stockCategory').value||'Tümü')}</p>`+tableHTML(stockHeaders,rows.map(p=>stockRow(p).map((v,i)=>[5,6,7,8,15,16,17].includes(i)?money(v):v))),true);}
function printReport(){renderReport();const content=$('reports').cloneNode(true);content.querySelectorAll('.no-print').forEach(x=>x.remove());return printDocument('Satış ve Kâr Raporu',`<p>Dönem: ${esc($('rf').value||'Başlangıç')} – ${esc($('rt').value||'Bugün')}</p>`+content.innerHTML,true);}
